/**
 * Centralized API Client Wrapper
 *
 * Wraps all openapi-fetch clients and provides:
 * - Request ID extraction from response headers (set by backend RequestIdFilter)
 * - Standardized error transformation to StructuredError format
 * - Unified error handling for all API calls
 *
 * All HTTP requests receive an X-Request-Id header from the backend filter.
 * We extract this header and include it in error responses for traceability.
 *
 * NOTE: Request IDs are ALWAYS generated by the backend RequestIdFilter.
 * If a request ID is missing, that's a programming error that must be fixed.
 * We do NOT use fallback IDs to make missing IDs immediately visible.
 */

import { subscriptionClient, workspaceClient } from './clients'
import { formatError, type FormattedError } from '@accounts/error-handling-web'

/**
 * Structured error response from the API.
 * Matches the format expected by formatError().
 */
export interface StructuredError {
  errorCode: string
  message: string
  details?: Record<string, unknown>
  timestamp: string
  requestId: string
}

/**
 * Response from apiClient methods.
 * Similar to openapi-fetch, but error is pre-formatted as FormattedError.
 */
export interface ApiResponse<T> {
  data?: T
  error?: FormattedError
  response: Response
}

/**
 * Extract request ID from response headers.
 * The backend's RequestIdFilter sets this header on all responses.
 *
 * IMPORTANT: If this returns undefined, that's a programming error.
 * The backend filter should ALWAYS set the X-Request-Id header.
 * We don't use fallback IDs to make issues visible immediately.
 */
function extractRequestId(response: Response): string | undefined {
  // Check both lowercase and capitalized versions
  return response.headers.get('x-request-id') || response.headers.get('X-Request-Id') || undefined
}

/**
 * Parse error response from fetch response object.
 * Handles both JSON error responses and non-JSON responses.
 *
 * Request ID is extracted from response headers (set by backend RequestIdFilter).
 * This is guaranteed to exist on all responses if the system is working correctly.
 *
 * Always captures HTTP status, request URL, and response body for debugging.
 */
async function parseErrorFromResponse(response: Response, requestId: string | undefined, method?: string, url?: string): Promise<FormattedError> {
  let responseBody: string | undefined
  let jsonError: unknown

  try {
    const text = await response.text()
    responseBody = text

    // Try to parse as JSON if we have a body
    if (text) {
      jsonError = JSON.parse(text)
    }
  } catch {
    // Response body is not JSON or couldn't be read
    if (responseBody === undefined) {
      responseBody = '(unable to read response body)'
    }
  }

  let formattedError: FormattedError

  if (jsonError && typeof jsonError === 'object' && 'errorCode' in jsonError) {
    // If response has errorCode, it's already structured
    const jsonObj = jsonError as any
    const structuredError: StructuredError = {
      errorCode: jsonObj.errorCode || 'UNKNOWN_ERROR',
      message: jsonObj.message || '',
      timestamp: jsonObj.timestamp || new Date().toISOString(),
      requestId: requestId || jsonObj.requestId || 'MISSING_REQUEST_ID',
      details: jsonObj.details,
    }
    formattedError = formatError(structuredError, response.status)
  } else {
    // Otherwise treat it as a generic error
    formattedError = formatError(jsonError, response.status)
  }

  // Always include debug information (HTTP status, request URL, response body)
  formattedError.httpStatus = response.status
  if (method && url) {
    formattedError.requestUrl = `${method} ${url}`
  }
  if (responseBody !== undefined) {
    formattedError.responseBody = responseBody
  }

  return formattedError
}

/**
 * Wrapper for openapi-fetch requests.
 * Injects request ID and transforms errors to FormattedError.
 *
 * Usage:
 *   const { data, error } = await apiClient.subscription.POST('/plans', { ... })
 *   if (error) {
 *     // error is already a FormattedError with requestId
 *     showErrorDialog(error)
 *   }
 */
class ApiClient {
  /**
   * Wrapper for subscription service client
   */
  readonly subscription = this.createClientWrapper(subscriptionClient)

  /**
   * Wrapper for workspace service client
   */
  readonly workspace = this.createClientWrapper(workspaceClient)

  /**
   * Create a wrapper around an openapi-fetch client.
   * Intercepts responses and transforms errors.
   */
  private createClientWrapper(client: any) {
    return {
      GET: async <T,>(url: string, options?: any): Promise<ApiResponse<T>> => {
        return this.makeRequest<T>(client, 'GET', url, options)
      },
      POST: async <T,>(url: string, options?: any): Promise<ApiResponse<T>> => {
        return this.makeRequest<T>(client, 'POST', url, options)
      },
      PUT: async <T,>(url: string, options?: any): Promise<ApiResponse<T>> => {
        return this.makeRequest<T>(client, 'PUT', url, options)
      },
      DELETE: async <T,>(url: string, options?: any): Promise<ApiResponse<T>> => {
        return this.makeRequest<T>(client, 'DELETE', url, options)
      },
      PATCH: async <T,>(url: string, options?: any): Promise<ApiResponse<T>> => {
        return this.makeRequest<T>(client, 'PATCH', url, options)
      },
      HEAD: async <T,>(url: string, options?: any): Promise<ApiResponse<T>> => {
        return this.makeRequest<T>(client, 'HEAD', url, options)
      },
    }
  }

  /**
   * Make an HTTP request through openapi-fetch client.
   * Extracts request ID from response headers and transforms errors.
   * Captures debug info (HTTP status, request URL, response body) when debug mode is enabled.
   */
  private async makeRequest<T,>(
    client: any,
    method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'HEAD',
    url: string,
    options?: any
  ): Promise<ApiResponse<T>> {
    try {
      // Make the request through openapi-fetch client
      const { data, error, response } = await client[method](url, options)

      // Extract request ID from response headers (set by backend RequestIdFilter)
      const requestId = extractRequestId(response)

      // If openapi-fetch returned an error OR the response status is 4xx/5xx, transform it.
      // openapi-fetch may leave `error` falsy for empty bodies (e.g. 400 with no body),
      // so we must also check the HTTP status directly.
      if (error || response.status >= 400) {
        // Use the error object parsed by openapi-fetch if available (response body was already consumed)
        let formattedError: FormattedError

        if (error && typeof error === 'object' && 'errorCode' in error) {
          // openapi-fetch already parsed the error response
          const structuredError: StructuredError = {
            errorCode: (error as any).errorCode || 'UNKNOWN_ERROR',
            message: (error as any).message || '',
            timestamp: (error as any).timestamp || new Date().toISOString(),
            requestId: requestId || (error as any).requestId || 'MISSING_REQUEST_ID',
            details: (error as any).details,
          }
          formattedError = formatError(structuredError, response.status)
        } else {
          // Fall back to parsing response (for non-JSON responses)
          formattedError = await parseErrorFromResponse(response, requestId, method, url)
        }

        // Always include debug information
        formattedError.httpStatus = response.status
        formattedError.requestUrl = `${method} ${url}`

        return {
          error: formattedError,
          response,
        }
      }

      // Success case
      return {
        data,
        response,
      }
    } catch (err) {
      // Unexpected error (e.g., network error, CORS block, JSON parse error)
      console.error('[apiClient] network/CORS error caught:', err)
      const formattedError = formatError(err)
      formattedError.httpStatus = 0
      formattedError.requestUrl = `${method} ${url}`
      formattedError.responseBody = err instanceof Error ? err.message : String(err)

      return {
        error: formattedError,
        response: new Response(null, { status: 503 }),
      }
    }
  }
}

/**
 * Singleton instance of the centralized API client.
 * Use this for all API requests to ensure unified error handling.
 *
 * Example:
 *   const { data, error } = await apiClient.subscription.POST('/plans', { ... })
 *   if (error) {
 *     console.log(`Error [${error.errorCode}]: ${error.userMessage}`)
 *     if (error.isRetryable) {
 *       // Show retry button
 *     }
 *   }
 */
export const apiClient = new ApiClient()
