/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all subscription plans
         * @description Retrieves all active subscription plans in the system.
         *     Plans are immutable templates created at system deployment (Free Trial, Starter, Professional, Enterprise).
         *     See REQ-PLAN-01 through REQ-PLAN-04.
         */
        get: operations["listPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get subscription plan by ID
         * @description Retrieves a specific subscription plan by its unique identifier.
         *     Returns plan details including features and quotas. See REQ-PLAN-02.
         */
        get: operations["getPlanById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new subscription
         * @description Creates a new subscription for an organization, linking it to a plan.
         *     Subscription starts immediately with the provided (or default) start and expiration dates.
         *     See REQ-SUB-01, REQ-SUB-07 (upgrade/downgrade).
         */
        post: operations["createSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get subscription by ID
         * @description Retrieves a subscription by its unique identifier.
         *     Returns full subscription details including embedded plan and status. See REQ-SUB-01.
         */
        get: operations["getSubscriptionById"];
        /**
         * Update or upgrade/downgrade subscription
         * @description Updates an existing subscription. Can change the plan (upgrade/downgrade, effective immediately),
         *     modify expiration date, or toggle auto-renewal. See REQ-SUB-07, REQ-SUB-08, REQ-SUB-09.
         */
        put: operations["updateSubscription"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/organization/{orgId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get active subscription for organization
         * @description Retrieves the currently active subscription for an organization.
         *     Returns the single active subscription (at most one per organization) with full plan details.
         *     Used by the Organization Service to fetch current subscription. See REQ-SUB-02, REQ-SUB-03.
         */
        get: operations["getOrganizationSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate subscription and get quotas
         * @description Returns subscription status, plan quotas, current usage, and remaining quota.
         *     Used by the Subscription Validation Filter to enforce access control and quota limits.
         *     This endpoint is highly cacheable (5-minute TTL recommended) for performance (REQ-FILTER-07: <5ms).
         *     See REQ-SUB-11, REQ-SUB-12, REQ-QUOTA-01 through REQ-QUOTA-04.
         */
        get: operations["validateSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/organization/{orgId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate subscription for an organization
         * @description Returns subscription status, plan quotas, current usage, and remaining quota for the
         *     organization's active subscription. Used by the Gateway Subscription Validation Filter
         *     to enforce access control and quota limits without requiring the subscription ID.
         *     This endpoint is highly cacheable (5-minute TTL recommended) for performance.
         *     See REQ-SUB-11, REQ-SUB-12, REQ-QUOTA-01 through REQ-QUOTA-04.
         */
        get: operations["validateOrganizationSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotas/organization/{orgId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get quota usage for organization
         * @description Returns current usage breakdown for an organization:
         *     - Active users (count from User Service)
         *     - Transactions created this month (reset monthly on 1st UTC)
         *     - API calls this month (reset monthly on 1st UTC)
         *     Includes quota limits and percentage utilization for billing/analytics.
         *     See REQ-QUOTA-01 through REQ-QUOTA-03.
         */
        get: operations["getOrganizationQuotaUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Immutable subscription plan template defining features and quotas.
         *     Plans are pre-seeded at system deployment (Free Trial, Starter, Professional, Enterprise).
         *     See REQ-PLAN-01, REQ-PLAN-02.
         */
        Plan: {
            /**
             * Format: uuid
             * @description System-generated unique plan identifier
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            readonly id: string;
            /**
             * @description Plan name (e.g., "Free Trial", "Starter", "Professional", "Enterprise")
             * @example Professional
             */
            name: string;
            /**
             * @description Brief plan description
             * @example Ideal for growing teams with advanced features
             */
            description: string;
            /**
             * Format: double
             * @description Monthly subscription cost in USD (null for Free Trial)
             * @example 99
             */
            monthlyPrice?: number | null;
            /**
             * Format: double
             * @description Annual subscription cost in USD (null for Free Trial)
             * @example 990
             */
            annualPrice?: number | null;
            /**
             * @description Feature flags defining what is enabled in this plan
             * @example {
             *       "canCreateWorkspaces": true,
             *       "canCreateUsers": true,
             *       "advancedReporting": true,
             *       "customBranding": true,
             *       "sso": false,
             *       "supportLevel": "premium"
             *     }
             */
            features: {
                [key: string]: boolean;
            };
            quotas: components["schemas"]["Quotas"];
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of plan creation (UTC)
             * @example 2026-01-01T00:00:00Z
             */
            readonly createdAt?: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of last modification (UTC)
             * @example 2026-01-01T00:00:00Z
             */
            readonly modifiedAt?: string;
        };
        /**
         * @description Quota limits for a plan. Null values indicate unlimited quota.
         *     See REQ-PLAN-03.
         */
        Quotas: {
            /**
             * @description Maximum active users in organization (null = unlimited)
             * @example 25
             */
            maxUsers?: number | null;
            /**
             * @description Maximum transactions per calendar month across all workspaces (null = unlimited)
             * @example 5000
             */
            maxTransactionsPerMonth?: number | null;
            /**
             * @description API rate limit in requests per minute per organization (null = unlimited)
             * @example 300
             */
            apiRateLimit?: number | null;
        };
        /**
         * @description Organization-plan linkage with status and validity dates.
         *     Each organization has at most one active subscription at a time.
         *     Contains embedded full Plan object (no need for separate plan fetch).
         *     See REQ-SUB-01 through REQ-SUB-10.
         */
        Subscription: {
            /**
             * Format: uuid
             * @description System-generated unique subscription identifier
             * @example 660e8400-e29b-41d4-a716-446655440002
             */
            readonly id: string;
            /**
             * Format: uuid
             * @description Link to organization
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            organizationId: string;
            /**
             * Format: uuid
             * @description Link to subscription plan
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            planId: string;
            plan: components["schemas"]["Plan"];
            /**
             * @description Subscription status. ACTIVE = within validity period and not cancelled/suspended.
             *     EXPIRED = past expiration date. CANCELLED = user/admin initiated.
             *     SUSPENDED = payment or compliance issue.
             *     See REQ-SUB-03.
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "EXPIRED" | "CANCELLED" | "SUSPENDED";
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of subscription start (UTC)
             * @example 2026-03-15T00:00:00Z
             */
            startDate: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of subscription expiration (UTC)
             * @example 2026-04-15T00:00:00Z
             */
            expirationDate: string;
            /**
             * @description Whether subscription auto-renews on expiration. See REQ-SUB-09.
             * @default false
             * @example true
             */
            autoRenew: boolean;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of subscription creation (UTC)
             * @example 2026-03-15T10:30:00Z
             */
            readonly createdAt: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of last modification (UTC)
             * @example 2026-03-15T10:30:00Z
             */
            readonly modifiedAt: string;
        };
        /** @description Request to create a new subscription for an organization. See REQ-SUB-01. */
        CreateSubscriptionRequest: {
            /**
             * Format: uuid
             * @description Target organization ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            organizationId: string;
            /**
             * Format: uuid
             * @description Target plan ID
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            planId: string;
            /**
             * Format: date-time
             * @description Subscription start date (optional, defaults to now). ISO 8601 UTC.
             * @example 2026-03-15T00:00:00Z
             */
            startDate?: string | null;
            /**
             * Format: date-time
             * @description Subscription expiration date (optional, defaults to 30 days from start). ISO 8601 UTC.
             * @example 2026-04-15T00:00:00Z
             */
            expirationDate?: string | null;
            /**
             * @description Whether subscription should auto-renew on expiration
             * @default false
             * @example true
             */
            autoRenew: boolean;
        };
        /**
         * @description Request to update a subscription (plan, dates, renewal settings).
         *     Can be used to upgrade/downgrade plans (effective immediately, REQ-SUB-08).
         *     All fields optional; only provided fields are updated.
         */
        UpdateSubscriptionRequest: {
            /**
             * Format: uuid
             * @description New plan ID (to upgrade/downgrade)
             * @example 550e8400-e29b-41d4-a716-446655440003
             */
            planId?: string;
            /**
             * Format: date-time
             * @description New expiration date. ISO 8601 UTC.
             * @example 2026-05-15T00:00:00Z
             */
            expirationDate?: string;
            /**
             * @description Update auto-renewal flag
             * @example false
             */
            autoRenew?: boolean;
        };
        /**
         * @description Response from subscription validation endpoint (/subscriptions/{id}/validate).
         *     Used by the Subscription Validation Filter to enforce access control and quota limits.
         *     Includes subscription status, plan quotas, current usage, and remaining quota (computed).
         *     See REQ-FILTER-05, REQ-FILTER-06, REQ-QUOTA-01.
         */
        SubscriptionValidationResponse: {
            /**
             * Format: uuid
             * @description The subscription's unique ID
             * @example 660e8400-e29b-41d4-a716-446655440002
             */
            subscriptionId: string;
            /**
             * Format: uuid
             * @description The organization's unique ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            organizationId: string;
            /**
             * @description Current subscription status
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "EXPIRED" | "CANCELLED" | "SUSPENDED";
            plan: components["schemas"]["Plan"];
            quotas: components["schemas"]["Quotas"];
            /** @description Current usage breakdown for the organization */
            usage: {
                /**
                 * @description Count of currently active users in organization
                 * @example 12
                 */
                activeUsers: number;
                /**
                 * @description Count of transactions created in current calendar month
                 * @example 342
                 */
                transactionsThisMonth: number;
                /**
                 * @description Count of API calls made this month
                 * @example 5230
                 */
                apiCallsThisMonth: number;
            };
            /**
             * @description Computed remaining quota (quota limit - current usage).
             *     Null values indicate unlimited (quota was null).
             */
            remainingQuota: {
                /**
                 * @description Remaining user slots (null if unlimited)
                 * @example 13
                 */
                remainingUsers?: number | null;
                /**
                 * @description Remaining transactions this month (null if unlimited)
                 * @example 4658
                 */
                remainingTransactions?: number | null;
                /**
                 * @description Remaining API calls this month (null if unlimited)
                 * @example null
                 */
                remainingApiCalls?: number | null;
            };
        };
        /**
         * @description Quota usage breakdown for an organization.
         *     Includes current usage, quota limits, and percentage utilization.
         *     Used for billing/analytics and quota alerts (REQ-QUOTA-04).
         *     See REQ-QUOTA-01, REQ-QUOTA-02, REQ-QUOTA-03.
         */
        QuotaUsageResponse: {
            /**
             * Format: uuid
             * @description The organization's unique ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            organizationId: string;
            /**
             * Format: uuid
             * @description The active plan's ID
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            planId: string;
            /**
             * @description Current active user count
             * @example 12
             */
            activeUsers: number;
            /**
             * @description User quota limit (null = unlimited)
             * @example 25
             */
            maxUsers: number | null;
            /**
             * Format: double
             * @description Percentage of user quota used (0-100, null if unlimited)
             * @example 48
             */
            usersPercentage?: number;
            /**
             * @description Transaction count in current calendar month (UTC)
             * @example 342
             */
            transactionsThisMonth: number;
            /**
             * @description Transaction quota limit per month (null = unlimited)
             * @example 5000
             */
            maxTransactionsPerMonth: number | null;
            /**
             * Format: double
             * @description Percentage of monthly transaction quota used (0-100, null if unlimited)
             * @example 6.84
             */
            transactionsPercentage?: number;
            /**
             * @description API call count in current calendar month (UTC)
             * @example 5230
             */
            apiCallsThisMonth: number;
            /**
             * @description API rate limit in requests per minute (null = unlimited)
             * @example 300
             */
            apiRateLimit: number | null;
            /**
             * Format: double
             * @description Percentage of monthly API quota used (0-100, null if unlimited)
             * @example 87.17
             */
            apiCallsPercentage?: number;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of last monthly counter reset (UTC 00:00 on 1st of month)
             * @example 2026-04-01T00:00:00Z
             */
            lastResetDate: string;
        };
        /** @description Standard error response format. Matches pattern in organization-api.yaml. */
        ErrorResponse: {
            /**
             * @description Error code or human-readable error message
             * @example Subscription not found
             */
            error: string;
            /**
             * @description Additional error details
             * @example No subscription with ID 660e8400-e29b-41d4-a716-446655440002 exists
             */
            message?: string;
            /**
             * @description Optional subscription status (for subscription-related errors)
             * @example EXPIRED
             * @enum {string}
             */
            subscriptionStatus?: "ACTIVE" | "EXPIRED" | "CANCELLED" | "SUSPENDED";
            /**
             * @description Optional quota type for quota-related errors (e.g., "users", "transactions")
             * @example transactions
             */
            quotaType?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description The plan's internal UUID */
        PlanId: string;
        /** @description The subscription's internal UUID */
        SubscriptionId: string;
        /** @description The organization's internal UUID */
        OrganizationId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all subscription plans */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"][];
                };
            };
        };
    };
    getPlanById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The plan's internal UUID */
                id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription plan found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Plan not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Subscription created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            /** @description Validation error (missing or invalid fields) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Organization or plan not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSubscriptionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The subscription's internal UUID */
                id: components["parameters"]["SubscriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The subscription's internal UUID */
                id: components["parameters"]["SubscriptionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Subscription updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            /** @description Validation error (invalid fields) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Subscription or plan not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOrganizationSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The organization's internal UUID */
                orgId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active subscription found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            /** @description Organization has no active subscription */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    validateSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The subscription's internal UUID */
                id: components["parameters"]["SubscriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription validation response with status, quotas, and usage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionValidationResponse"];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    validateOrganizationSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The organization's internal UUID */
                orgId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription validation response with status, quotas, and usage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionValidationResponse"];
                };
            };
            /** @description Organization has no active subscription */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOrganizationQuotaUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The organization's internal UUID */
                orgId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quota usage breakdown for organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaUsageResponse"];
                };
            };
            /** @description Organization not found or has no active subscription */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
